apiVersion: v1
kind: Service
metadata:
  name: podinfo-backend
  labels:
    app: podinfo-backend
spec:
  type: ClusterIP
  selector:
    app: podinfo-backend
  ports:
    - port: 9898
      targetPort: 9898
      protocol: TCP
      name: http
